services:
  notebook:
    image: my-ml-notebook
    container_name: notebook_container
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      - APP_ENV=production

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
